In [4]:
import numpy as np
import pandas as pd
import ast

In [6]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [8]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

# Data Pre-processing

In [9]:
movies.merge(credits , on='title').shape

(4809, 23)

In [10]:
movies.shape

(4803, 20)

In [11]:
credits.shape

(4803, 4)

In [12]:
movies = movies.merge(credits , on='title')

In [13]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [14]:
#  now we'll select important features for recommendation of movies and drop the
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [15]:
# we'll keep --> genres id keywords title overview cast crew
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [16]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [17]:
# check for missing n duplicate data
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [18]:
movies.dropna(inplace=True)

In [19]:
movies.duplicated().sum()

0

In [20]:
# let's see 1st entry of genre column
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [21]:
# but we only want --> [ 'Action' , 'Adventure' , 'Fantasy' , 'SciFi' ]
def object(obj):    # helper fn
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [22]:
#  but DT of above genres is string of list...so we'll first convert that into l
movies['genres'] = movies['genres'].apply(object)
movies['keywords'] = movies['keywords'].apply(object)

In [23]:
movies.head(1)
#  content is same but DT is different

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [24]:
#  we'll only consider top 3 members from cast

def convert3(obj):     # helper fn
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [25]:
movies['cast'] = movies['cast'].apply(convert3)

In [26]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [27]:
#  we'll only fetch director from crew

def fetch_director(obj):             # helper fn
    L=[]
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [28]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [30]:
# now adjusting overview column --> converting into list
# and removing space from single entity like : Sam Worthington --> SamWorthington

movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(' ','') for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(' ','') for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(' ','') for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(' ','') for i in x])

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [32]:
# now creating column tags : 
movies['tags'] = movies['overview'] + movies['genres'] + movies['cast'] + movies['crew']

In [33]:
new_df = movies[['movie_id','title','tags']]

In [34]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [35]:
# now converting list into string (under tags)
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [36]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\bhavy\AppData\Local\Temp\ipykernel_20824\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [37]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [38]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [39]:
# converting the complete line into lower case
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\bhavy\AppData\Local\Temp\ipykernel_20824\3073891067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [40]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

# Text Vectorization

In [41]:
print(new_df['tags'][0])
print('\n\n')
print(new_df['tags'][1])

in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver jamescameron



captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action johnnydepp orlandobloom keiraknightley goreverbinski

In [42]:
# every movie would be represented by a vector and model will recommend closest vector(movie) on basis of
# cosine similarity (angle between them)
# text --> vectors can be done by many ways (text vectorization): text vectors, bag of words , word2vec , tfidf

# we'll use bag of words : in this we'll combine every tag , now we got a big string (tag1 + tag2 ...)
# now we've to find 5000 (say) most common words from that large text
# now check occurence of words in movies so we'll get a 5000x5000 entry table...each record is a vector

# words -->  w1  w2  w3                                                 w5000
# movies :                       <occurence>
#   m1       2    3   5                                                    0
#   m2       0    0   3                                                    2
# 
# 
# 
# 
#   m5000    1    1   1                                                    5

# now we'll remove stop words like : is are or they it can also a an to the

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000 , stop_words='english')    # can see 5k top words via CV

In [43]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [44]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [45]:
vectors =cv.fit_transform(new_df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
len(cv.get_feature_names_out())

5000

In [48]:
cv.get_feature_names_out()    # after stemming no repeated words shall be there

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [49]:
# these are top 5k words but it has some words with almost same meaning: actions-action , activity-activities
# using NLP (stemming)
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [50]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [51]:
ps.stem('loving')

'love'

In [52]:
# stemming 1st tag for ex
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'
)

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav jamescameron'

In [53]:
new_df['tags'] = new_df['tags'].apply(stem)
# now repeating above steps

C:\Users\bhavy\AppData\Local\Temp\ipykernel_20824\1390429710.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [54]:
# cosine similarity ( eucledean distance is not a reliable measure in higher data )
# less theta between vectors--> more similar movies --> more cosine similarity

from sklearn.metrics.pairwise import cosine_similarity     # similarity inversly prop to distance

In [55]:
cosine_similarity(vectors)

array([[1.        , 0.15389675, 0.0860663 , ..., 0.        , 0.        ,
        0.        ],
       [0.15389675, 1.        , 0.08830216, ..., 0.03673592, 0.        ,
        0.        ],
       [0.0860663 , 0.08830216, 1.        , ..., 0.03081668, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03673592, 0.03081668, ..., 1.        , 0.07897472,
        0.02746175],
       [0.        , 0.        , 0.        , ..., 0.07897472, 1.        ,
        0.05638839],
       [0.        , 0.        , 0.        , ..., 0.02746175, 0.05638839,
        1.        ]])

In [56]:
cosine_similarity(vectors).shape

(4806, 4806)

In [57]:
similarity = cosine_similarity(vectors)

In [58]:
similarity     # it is an array of arrays

array([[1.        , 0.15389675, 0.0860663 , ..., 0.        , 0.        ,
        0.        ],
       [0.15389675, 1.        , 0.08830216, ..., 0.03673592, 0.        ,
        0.        ],
       [0.0860663 , 0.08830216, 1.        , ..., 0.03081668, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03673592, 0.03081668, ..., 1.        , 0.07897472,
        0.02746175],
       [0.        , 0.        , 0.        , ..., 0.07897472, 1.        ,
        0.05638839],
       [0.        , 0.        , 0.        , ..., 0.02746175, 0.05638839,
        1.        ]])

In [59]:
similarity[0]     # telling similarity of 1st movie with other

array([1.        , 0.15389675, 0.0860663 , ..., 0.        , 0.        ,
       0.        ])

In [60]:
sorted(similarity[0] , reverse=True)

[1.0000000000000002,
 0.26967994498529685,
 0.25819888974716115,
 0.24913643956121986,
 0.2480694691784169,
 0.2439750182371333,
 0.24152294576982397,
 0.22360679774997896,
 0.22360679774997894,
 0.22056438662814232,
 0.21926450482675733,
 0.21693045781865616,
 0.21693045781865616,
 0.21693045781865616,
 0.21213203435596426,
 0.21213203435596426,
 0.2076136996343499,
 0.20732210721568234,
 0.2051956704170308,
 0.2051956704170308,
 0.2051956704170308,
 0.20412414523193148,
 0.20377787840885372,
 0.20225995873897262,
 0.20080483222562473,
 0.19999999999999998,
 0.1976423537605237,
 0.19518001458970663,
 0.19518001458970663,
 0.19518001458970663,
 0.19364916731037088,
 0.19069251784911845,
 0.1889822365046136,
 0.1889822365046136,
 0.1889822365046136,
 0.18650096164806276,
 0.18650096164806276,
 0.18428853505018536,
 0.18257418583505539,
 0.18257418583505539,
 0.18257418583505539,
 0.18257418583505539,
 0.18257418583505539,
 0.18257418583505539,
 0.1813690625275029,
 0.17928429140015906,
 0.17928429140015906,
 0.17888543819998318,
 0.17888543819998318,
 0.17888543819998318,
 0.17677669529663687,
 0.17677669529663687,
 0.17677669529663687,
 0.17541160386140586,
 0.1732050807568877,
 0.1732050807568877,
 0.17213259316477408,
 0.17213259316477408,
 0.17213259316477408,
 0.17213259316477408,
 0.16854996561581054,
 0.16770509831248423,
 0.16770509831248423,
 0.16770509831248423,
 0.16770509831248423,
 0.16770509831248423,
 0.16770509831248423,
 0.16770509831248423,
 0.16770509831248423,
 0.16609095970747992,
 0.16609095970747992,
 0.16609095970747992,
 0.16609095970747992,
 0.16609095970747992,
 0.16484511834894675,
 0.1632993161855452,
 0.1632993161855452,
 0.1632993161855452,
 0.16269784336399212,
 0.16269784336399212,
 0.16269784336399212,
 0.16269784336399212,
 0.16269784336399212,
 0.16269784336399212,
 0.16269784336399212,
 0.16269784336399212,
 0.16269784336399212,
 0.16137430609197573,
 0.16137430609197573,
 0.16064386578049977,
 0.16064386578049977,
 0.16064386578049977,
 0.16064386578049977,
 0.16064386578049977,
 0.15971914124998499,
 0.15971914124998499,
 0.158113883008419,
 0.158113883008419,
 0.158113883008419,
 0.158113883008419,
 0.158113883008419,
 0.158113883008419,
 0.158113883008419,
 0.15811388300841894,
 0.15811388300841894,
 0.15655607277128736,
 0.1556997888323046,
 0.1556997888323046,
 0.1538967528127731,
 0.1538967528127731,
 0.1538967528127731,
 0.1538967528127731,
 0.1538967528127731,
 0.1538967528127731,
 0.1538967528127731,
 0.1538967528127731,
 0.1535737792084878,
 0.15339299776947407,
 0.15339299776947407,
 0.15339299776947407,
 0.15339299776947407,
 0.15339299776947407,
 0.15339299776947407,
 0.15339299776947407,
 0.15214515486254615,
 0.15118578920369088,
 0.15118578920369088,
 0.15118578920369088,
 0.15,
 0.15,
 0.15,
 0.15,
 0.15,
 0.15,
 0.15,
 0.14907119849998596,
 0.14907119849998596,
 0.14907119849998596,
 0.14907119849998596,
 0.14907119849998596,
 0.14704292441876154,
 0.14638501094227996,
 0.14638501094227996,
 0.14638501094227996,
 0.14638501094227996,
 0.14638501094227996,
 0.14638501094227996,
 0.14638501094227996,
 0.14638501094227996,
 0.14638501094227996,
 0.14509525002200233,
 0.14509525002200233,
 0.14509525002200233,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.14301938838683884,
 0.1414213562373095,
 0.1414213562373095,
 0.13987572123604708,
 0.13987572123604708,
 0.13987572123604708,
 0.13987572123604708,
 0.13987572123604708,
 0.13987572123604708,
 0.13987572123604708,
 0.13968605915391563,
 0.13801311186847084,
 0.13801311186847084,
 0.13693063937629155,
 0.13693063937629155,
 0.13693063937629155,
 0.13693063937629155,
 0.13693063937629155,
 0.13693063937629155,
 0.1363988678940947,
 0.1363988678940947,
 0.13483997249264842,
 0.13483997249264842,
 0.13483997249264842,
 0.13483997249264842,
 0.13483997249264842,
 0.1341640786499874,
 0.1341640786499874,
 0.1341640786499874,
 0.1341640786499874,
 0.1341640786499874,
 0.1341640786499874,
 0.1341640786499874,
 0.1341640786499874,
 0.1341640786499874,
 0.1341640786499874,
 0.13333333333333333,
 0.1318760946791574,
 0.1315587028960544,
 0.1315587028960544,
 0.1315587028960544,
 0.1315587028960544,
 0.1315587028960544,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358058,
 0.12909944487358055,
 0.12909944487358055,
 0.12909944487358055,
 0.12909944487358055,
 0.12909944487358055,
 0.12909944487358055,
 0.12909944487358055,
 0.12777531299998798,
 0.1267731382092775,
 0.1267731382092775,
 0.1267731382092775,
 0.1267731382092775,
 0.1267731382092775,
 0.1267731382092775,
 0.1267731382092775,
 0.1267731382092775,
 0.1267731382092775,
 0.12649110640673517,
 0.12524485821702988,
 0.12524485821702988,
 0.12456821978060995,
 0.12456821978060995,
 0.12456821978060995,
 0.12456821978060995,
 0.12456821978060995,
 0.12403473458920845,
 0.12403473458920845,
 0.12403473458920845,
 0.12403473458920845,
 0.12403473458920845,
 0.12403473458920845,
 0.12403473458920845,
 0.12403473458920845,
 0.12285902336679025,
 0.1224744871391589,
 0.1224744871391589,
 0.1224744871391589,
 0.1224744871391589,
 0.1224744871391589,
 0.1224744871391589,
 0.12171612389003691,
 0.12171612389003691,
 0.12060453783110545,
 0.12048289933537483,
 0.12048289933537483,
 0.12048289933537483,
 0.12048289933537483,
 0.12048289933537483,
 0.12048289933537483,
 0.12048289933537483,
 0.12048289933537483,
 0.12048289933537483,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343936,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11858541225631421,
 0.11744404390294068,
 0.11677484162422845,
 0.11677484162422844,
 0.11677484162422844,
 0.11677484162422844,
 0.11677484162422844,
 0.11677484162422844,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11547005383792514,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11504474832710555,
 0.11451966686277364,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11338934190276817,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498948,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11180339887498947,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.11028219331407116,
 0.10927167294163061,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10741723110591493,
 0.10741723110591492,
 0.10741723110591492,
 0.10741723110591492,
 0.10741723110591492,
 0.10741723110591492,
 0.10741723110591492,
 0.10741723110591492,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10606601717798213,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10540925533894599,
 0.10476454436543672,
 0.10476454436543672,
 0.10476454436543672,
 0.10476454436543672,
 0.10476454436543672,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.10350983390135313,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.1025978352085154,
 0.10229915092057101,
 0.10229915092057101,
 0.10112997936948631,
 0.10112997936948631,
 0.10112997936948631,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09999999999999999,
 0.09890707100936805,
 0.09890707100936805,
 0.09784921095801634,
 0.09784921095801634,
 0.09784921095801634,
 0.09784921095801634,
 0.09784921095801634,
 0.09784921095801634,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09759000729485331,
 0.09682458365518543,
 0.09682458365518543,
 0.09682458365518543,
 0.09682458365518543,
 0.09682458365518543,
 0.09583148474999098,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09534625892455922,
 0.09486832980505137,
 0.09486832980505137,
 0.0939336436627724,
 0.0939336436627724,
 0.0939336436627724,
 0.09376144618769908,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09302605094190634,
 0.09302605094190634,
 0.09302605094190634,
 0.09302605094190634,
 0.09302605094190634,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09128709291752768,
 0.09045340337332908,
 0.09045340337332908,
 0.09045340337332908,
 0.09045340337332908,
 0.08964214570007953,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08944271909999159,
 0.08899883189799696,
 0.08808303292720551,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08660254037844385,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08606629658238704,
 0.08588975014708022,
 0.08588975014708022,
 0.08519427513705971,
 0.08519427513705971,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285165,
 0.08451542547285164,
 0.08451542547285164,
 0.08385254915624211,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08257228238447704,
 0.08257228238447704,
 0.08195375470622296,
 0.08195375470622296,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.0816496580927726,
 0.08131156281817417,
 0.08075728530872482,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.07961173386514128,
 0.0790569415042095,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07905694150420947,
 0.07851358838853205,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.0778498944161523,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07669649888473704,
 0.07644707871564382,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.07559289460184544,
 0.075,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07453559924999298,
 0.07377111135633174,
 0.0736321040510724,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07352146220938077,
 0.07319250547113998,
 0.07276068751089988,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07191949522280762,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07161148740394328,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.0703210846407743,
 0.06984302957695782,
 0.06984302957695782,
 0.06984302957695782,
 0.06984302957695782,
 0.06984302957695782,
 0.06984302957695782,
 0.06984302957695782,
 0.06984302957695782,
 0.06984302957695782,
 0.06984302957695782,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06819943394704735,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,
 0.06741998624632421,

In [61]:
list(enumerate(similarity[0]))   # so created index position wrt distances (list of tuples)

[(0, 1.0000000000000002),
 (1, 0.1538967528127731),
 (2, 0.08606629658238704),
 (3, 0.05923488777590924),
 (4, 0.12048289933537483),
 (5, 0.15339299776947407),
 (6, 0.035355339059327376),
 (7, 0.22056438662814232),
 (8, 0.08944271909999159),
 (9, 0.11180339887498947),
 (10, 0.1632993161855452),
 (11, 0.11338934190276817),
 (12, 0.16269784336399212),
 (13, 0.07071067811865475),
 (14, 0.17213259316477408),
 (15, 0.07669649888473704),
 (16, 0.1224744871391589),
 (17, 0.13801311186847084),
 (18, 0.06030226891555272),
 (19, 0.11028219331407116),
 (20, 0.07961173386514128),
 (21, 0.08451542547285165),
 (22, 0.10846522890932808),
 (23, 0.15),
 (24, 0.08606629658238704),
 (25, 0.02795084971874737),
 (26, 0.18257418583505539),
 (27, 0.16137430609197573),
 (28, 0.1732050807568877),
 (29, 0.09784921095801634),
 (30, 0.11028219331407116),
 (31, 0.21693045781865616),
 (32, 0.0659380473395787),
 (33, 0.158113883008419),
 (34, 0.0),
 (35, 0.17928429140015906),
 (36, 0.1976423537605237),
 (37, 0.08770580193070293),
 (38, 0.08588975014708022),
 (39, 0.12909944487358055),
 (40, 0.08451542547285165),
 (41, 0.10476454436543672),
 (42, 0.0),
 (43, 0.15339299776947407),
 (44, 0.06741998624632421),
 (45, 0.12524485821702988),
 (46, 0.18257418583505539),
 (47, 0.15655607277128736),
 (48, 0.06030226891555272),
 (49, 0.0),
 (50, 0.12456821978060995),
 (51, 0.09045340337332908),
 (52, 0.12909944487358055),
 (53, 0.0778498944161523),
 (54, 0.06201736729460423),
 (55, 0.08660254037844385),
 (56, 0.158113883008419),
 (57, 0.0),
 (58, 0.06388765649999399),
 (59, 0.08451542547285164),
 (60, 0.0),
 (61, 0.2051956704170308),
 (62, 0.12909944487358058),
 (63, 0.0778498944161523),
 (64, 0.05590169943749474),
 (65, 0.03296902366978935),
 (66, 0.03627381250550058),
 (67, 0.12048289933537483),
 (68, 0.2051956704170308),
 (69, 0.04969039949999532),
 (70, 0.11180339887498947),
 (71, 0.10882143751650175),
 (72, 0.18650096164806276),
 (73, 0.07071067811865475),
 (74, 0.1556997888323046),
 (75, 0.09128709291752769),
 (76, 0.12048289933537483),
 (77, 0.0),
 (78, 0.09325048082403138),
 (79, 0.11338934190276817),
 (80, 0.05163977794943222),
 (81, 0.08075728530872482),
 (82, 0.09534625892455922),
 (83, 0.19364916731037088),
 (84, 0.1535737792084878),
 (85, 0.07319250547113998),
 (86, 0.0778498944161523),
 (87, 0.1315587028960544),
 (88, 0.1025978352085154),
 (89, 0.04170288281141495),
 (90, 0.09534625892455922),
 (91, 0.16609095970747992),
 (92, 0.07905694150420947),
 (93, 0.07453559924999298),
 (94, 0.21693045781865616),
 (95, 0.09534625892455922),
 (96, 0.12909944487358055),
 (97, 0.10741723110591492),
 (98, 0.16269784336399212),
 (99, 0.039528470752104736),
 (100, 0.05423261445466404),
 (101, 0.1315587028960544),
 (102, 0.12060453783110545),
 (103, 0.10476454436543672),
 (104, 0.09759000729485331),
 (105, 0.11547005383792514),
 (106, 0.07352146220938077),
 (107, 0.1318760946791574),
 (108, 0.11338934190276817),
 (109, 0.12909944487358058),
 (110, 0.0),
 (111, 0.12909944487358055),
 (112, 0.08944271909999159),
 (113, 0.07905694150420947),
 (114, 0.0778498944161523),
 (115, 0.08606629658238704),
 (116, 0.08304547985373996),
 (117, 0.10540925533894599),
 (118, 0.02862991671569341),
 (119, 0.042257712736425826),
 (120, 0.0),
 (121, 0.12456821978060995),
 (122, 0.158113883008419),
 (123, 0.13987572123604708),
 (124, 0.06900655593423542),
 (125, 0.06674912392349772),
 (126, 0.11858541225631421),
 (127, 0.16770509831248423),
 (128, 0.0),
 (129, 0.10350983390135313),
 (130, 0.044721359549995794),
 (131, 0.14704292441876154),
 (132, 0.07254762501100116),
 (133, 0.049999999999999996),
 (134, 0.16770509831248423),
 (135, 0.0),
 (136, 0.03726779962499649),
 (137, 0.023186944788008413),
 (138, 0.14638501094227996),
 (139, 0.15339299776947407),
 (140, 0.06984302957695782),
 (141, 0.06454972243679029),
 (142, 0.09325048082403138),
 (143, 0.09784921095801634),
 (144, 0.1025978352085154),
 (145, 0.03261640365267211),
 (146, 0.0),
 (147, 0.0816496580927726),
 (148, 0.1538967528127731),
 (149, 0.17677669529663687),
 (150, 0.18257418583505539),
 (151, 0.26967994498529685),
 (152, 0.09999999999999999),
 (153, 0.09128709291752768),
 (154, 0.04767312946227961),
 (155, 0.0),
 (156, 0.03892494720807615),
 (157, 0.10540925533894599),
 (158, 0.14907119849998596),
 (159, 0.11180339887498948),
 (160, 0.08519427513705971),
 (161, 0.07453559924999298),
 (162, 0.049999999999999996),
 (163, 0.07905694150420947),
 (164, 0.11858541225631421),
 (165, 0.1025978352085154),
 (166, 0.14638501094227996),
 (167, 0.08944271909999159),
 (168, 0.15118578920369088),
 (169, 0.10882143751650175),
 (170, 0.10476454436543672),
 (171, 0.039528470752104736),
 (172, 0.11952286093343936),
 (173, 0.0),
 (174, 0.17541160386140586),
 (175, 0.08032193289024989),
 (176, 0.05773502691896257),
 (177, 0.0),
 (178, 0.03779644730092272),
 (179, 0.05423261445466404),
 (180, 0.03726779962499649),
 (181, 0.0408248290463863),
 (182, 0.11858541225631421),
 (183, 0.09682458365518543),
 (184, 0.11028219331407116),
 (185, 0.08451542547285165),
 (186, 0.06454972243679029),
 (187, 0.15339299776947407),
 (188, 0.035355339059327376),
 (189, 0.05976143046671968),
 (190, 0.06030226891555272),
 (191, 0.0816496580927726),
 (192, 0.0),
 (193, 0.08808303292720551),
 (194, 0.0),
 (195, 0.08944271909999159),
 (196, 0.09999999999999999),
 (197, 0.06984302957695782),
 (198, 0.09128709291752769),
 (199, 0.20080483222562473),
 (200, 0.1414213562373095),
 (201, 0.0),
 (202, 0.052704627669472995),
 (203, 0.1315587028960544),
 (204, 0.04016096644512494),
 (205, 0.10540925533894599),
 (206, 0.16137430609197573),
 (207, 0.13693063937629155),
 (208, 0.20225995873897262),
 (209, 0.052704627669472995),
 (210, 0.0778498944161523),
 (211, 0.03892494720807615),
 (212, 0.11677484162422844),
 (213, 0.11180339887498947),
 (214, 0.03779644730092272),
 (215, 0.12048289933537483),
 (216, 0.11180339887498948),
 (217, 0.06388765649999399),
 (218, 0.05976143046671968),
 (219, 0.09128709291752769),
 (220, 0.08944271909999159),
 (221, 0.03726779962499649),
 (222, 0.09045340337332908),
 (223, 0.07559289460184544),
 (224, 0.061429511683395124),
 (225, 0.0778498944161523),
 (226, 0.0),
 (227, 0.09534625892455922),
 (228, 0.1414213562373095),
 (229, 0.07851358838853205),
 (230, 0.11952286093343936),
 (231, 0.0),
 (232, 0.19518001458970663),
 (233, 0.158113883008419),
 (234, 0.10741723110591492),
 (235, 0.08770580193070293),
 (236, 0.09534625892455922),
 (237, 0.09759000729485331),
 (238, 0.12171612389003691),
 (239, 0.061429511683395124),
 (240, 0.08606629658238704),
 (241, 0.1224744871391589),
 (242, 0.13693063937629155),
 (243, 0.11677484162422844),
 (244, 0.049999999999999996),
 (245, 0.09999999999999999),
 (246, 0.03450327796711771),
 (247, 0.0),
 (248, 0.07071067811865475),
 (249, 0.11547005383792514),
 (250, 0.0),
 (251, 0.0),
 (252, 0.035355339059327376),
 (253, 0.06030226891555272),
 (254, 0.08304547985373996),
 (255, 0.0),
 (256, 0.13483997249264842),
 (257, 0.08606629658238704),
 (258, 0.03131121455425747),
 (259, 0.1025978352085154),
 (260, 0.1538967528127731),
 (261, 0.045643546458763846),
 (262, 0.11858541225631421),
 (263, 0.15),
 (264, 0.0),
 (265, 0.045643546458763846),
 (266, 0.09999999999999999),
 (267, 0.10846522890932808),
 (268, 0.042257712736425826),
 (269, 0.0),
 (270, 0.1267731382092775),
 (271, 0.11858541225631421),
 (272, 0.0),
 (273, 0.03834824944236852),
 (274, 0.046373889576016826),
 (275, 0.15),
 (276, 0.1025978352085154),
 (277, 0.09682458365518543),
 (278, 0.11504474832710555),
 (279, 0.11180339887498947),
 (280, 0.0),
 (281, 0.07559289460184544),
 (282, 0.08770580193070293),
 (283, 0.0),
 (284, 0.0),
 (285, 0.031008683647302113),
 (286, 0.03627381250550058),
 (287, 0.0),
 (288, 0.0),
 (289, 0.07161148740394328),
 (290, 0.09534625892455922),
 (291, 0.08451542547285165),
 (292, 0.1538967528127731),
 (293, 0.04767312946227961),
 (294, 0.08304547985373996),
 (295, 0.042257712736425826),
 (296, 0.06900655593423542),
 (297, 0.03726779962499649),
 (298, 0.0),
 (299, 0.06388765649999399),
 (300, 0.1267731382092775),
 (301, 0.09128709291752768),
 (302, 0.08451542547285165),
 (303, 0.04152273992686998),
 (304, 0.04850712500726659),
 (305, 0.11180339887498947),
 (306, 0.08770580193070293),
 (307, 0.09376144618769908),
 (308, 0.05423261445466404),
 (309, 0.09999999999999999),
 (310, 0.05547001962252292),
 (311, 0.16064386578049977),
 (312, 0.14509525002200233),
 (313, 0.05590169943749474),
 (314, 0.0),
 (315, 0.1267731382092775),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.09999999999999999),
 (320, 0.04767312946227961),
 (321, 0.0),
 (322, 0.2051956704170308),
 (323, 0.0),
 (324, 0.03726779962499649),
 (325, 0.09128709291752769),
 (326, 0.04303314829119352),
 (327, 0.045643546458763846),
 (328, 0.0),
 (329, 0.13693063937629155),
 (330, 0.16269784336399212),
 (331, 0.06819943394704735),
 (332, 0.1267731382092775),
 (333, 0.04879500364742666),
 (334, 0.11504474832710555),
 (335, 0.08606629658238704),
 (336, 0.1025978352085154),
 (337, 0.03580574370197164),
 (338, 0.0),
 (339, 0.09128709291752769),
 (340, 0.0816496580927726),
 (341, 0.09128709291752769),
 (342, 0.10927167294163061),
 (343, 0.032274861218395144),
 (344, 0.042257712736425826),
 (345, 0.03162277660168379),
 (346, 0.0),
 (347, 0.0),
 (348, 0.04767312946227961),
 (349, 0.1341640786499874),
 (350, 0.07352146220938077),
 (351, 0.0),
 (352, 0.045643546458763846),
 (353, 0.033709993123162106),
 (354, 0.0),
 (355, 0.06324555320336758),
 (356, 0.09534625892455922),
 (357, 0.0),
 (358, 0.09759000729485331),
 (359, 0.04767312946227961),
 (360, 0.0),
 (361, 0.04303314829119352),
 (362, 0.09128709291752769),
 (363, 0.06741998624632421),
 (364, 0.036760731104690386),
 (365, 0.08304547985373996),
 (366, 0.08032193289024989),
 (367, 0.0),
 (368, 0.09534625892455922),
 (369, 0.1267731382092775),
 (370, 0.09128709291752769),
 (371, 0.10476454436543672),
 (372, 0.07905694150420947),
 (373, 0.11547005383792514),
 (374, 0.06324555320336758),
 (375, 0.030714755841697562),
 (376, 0.07352146220938077),
 (377, 0.0),
 (378, 0.0),
 (379, 0.07191949522280762),
 (380, 0.0),
 (381, 0.12403473458920845),
 (382, 0.0),
 (383, 0.08032193289024989),
 (384, 0.045643546458763846),
 (385, 0.0),
 (386, 0.03779644730092272),
 (387, 0.04303314829119352),
 (388, 0.0),
 (389, 0.09128709291752769),
 (390, 0.044721359549995794),
 (391, 0.02988071523335984),
 (392, 0.043852900965351466),
 (393, 0.0),
 (394, 0.039528470752104736),
 (395, 0.0),
 (396, 0.04016096644512494),
 (397, 0.0),
 (398, 0.0),
 (399, 0.039528470752104736),
 (400, 0.15),
 (401, 0.0),
 (402, 0.07905694150420947),
 (403, 0.15971914124998499),
 (404, 0.049999999999999996),
 (405, 0.04662524041201569),
 (406, 0.03162277660168379),
 (407, 0.031008683647302113),
 (408, 0.05423261445466404),
 (409, 0.0),
 (410, 0.10606601717798213),
 (411, 0.0778498944161523),
 (412, 0.13483997249264842),
 (413, 0.11504474832710555),
 (414, 0.04152273992686998),
 (415, 0.05872202195147034),
 (416, 0.045643546458763846),
 (417, 0.052704627669472995),
 (418, 0.0),
 (419, 0.10606601717798213),
 (420, 0.1813690625275029),
 (421, 0.0),
 (422, 0.12909944487358058),
 (423, 0.04016096644512494),
 (424, 0.06324555320336758),
 (425, 0.0816496580927726),
 (426, 0.08451542547285164),
 (427, 0.0408248290463863),
 (428, 0.05773502691896257),
 (429, 0.0),
 (430, 0.04152273992686998),
 (431, 0.04662524041201569),
 (432, 0.07559289460184544),
 (433, 0.04879500364742666),
 (434, 0.0),
 (435, 0.05423261445466404),
 (436, 0.0),
 (437, 0.042257712736425826),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.04662524041201569),
 (442, 0.07905694150420947),
 (443, 0.039528470752104736),
 (444, 0.0),
 (445, 0.0),
 (446, 0.043852900965351466),
 (447, 0.035355339059327376),
 (448, 0.0),
 (449, 0.09534625892455922),
 (450, 0.03726779962499649),
 (451, 0.039528470752104736),
 (452, 0.04879500364742666),
 (453, 0.04016096644512494),
 (454, 0.08304547985373996),
 (455, 0.052704627669472995),
 (456, 0.06741998624632421),
 (457, 0.07352146220938077),
 (458, 0.032274861218395144),
 (459, 0.05590169943749474),
 (460, 0.0),
 (461, 0.14301938838683884),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.19999999999999998),
 (467, 0.12524485821702988),
 (468, 0.045643546458763846),
 (469, 0.06523280730534423),
 (470, 0.03834824944236852),
 (471, 0.07559289460184544),
 (472, 0.11504474832710555),
 (473, 0.11504474832710555),
 (474, 0.0),
 (475, 0.10350983390135313),
 (476, 0.09999999999999999),
 (477, 0.0),
 (478, 0.06666666666666667),
 (479, 0.026919095102908273),
 (480, 0.07559289460184544),
 (481, 0.0),
 (482, 0.0),
 (483, 0.19518001458970663),
 (484, 0.049999999999999996),
 (485, 0.08451542547285165),
 (486, 0.08195375470622296),
 (487, 0.16770509831248423),
 (488, 0.0790569415042095),
 (489, 0.0),
 (490, 0.1732050807568877),
 (491, 0.06900655593423542),
 (492, 0.04152273992686998),
 (493, 0.0),
 (494, 0.0),
 (495, 0.22360679774997896),
 (496, 0.0),
 (497, 0.0),
 (498, 0.1025978352085154),
 (499, 0.0),
 (500, 0.0408248290463863),
 (501, 0.07254762501100116),
 (502, 0.07254762501100116),
 (503, 0.08451542547285165),
 (504, 0.0),
 (505, 0.16269784336399212),
 (506, 0.0),
 (507, 0.17677669529663687),
 (508, 0.16064386578049977),
 (509, 0.036760731104690386),
 (510, 0.08770580193070293),
 (511, 0.14638501094227996),
 (512, 0.043852900965351466),
 (513, 0.11858541225631421),
 (514, 0.039528470752104736),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.07352146220938077),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.07071067811865475),
 (524, 0.0),
 (525, 0.0408248290463863),
 (526, 0.0),
 (527, 0.0),
 (528, 0.039528470752104736),
 (529, 0.16854996561581054),
 (530, 0.04767312946227961),
 (531, 0.06984302957695782),
 (532, 0.0),
 (533, 0.05423261445466404),
 (534, 0.05773502691896257),
 (535, 0.11028219331407116),
 (536, 0.0),
 (537, 0.10846522890932808),
 (538, 0.0),
 (539, 0.18650096164806276),
 (540, 0.07669649888473704),
 (541, 0.06085806194501846),
 (542, 0.05725983343138682),
 (543, 0.10350983390135313),
 (544, 0.09128709291752769),
 (545, 0.0408248290463863),
 (546, 0.052704627669472995),
 (547, 0.11180339887498948),
 (548, 0.0),
 (549, 0.07352146220938077),
 (550, 0.0),
 (551, 0.035355339059327376),
 (552, 0.0),
 (553, 0.05423261445466404),
 (554, 0.0),
 (555, 0.024253562503633294),
 (556, 0.04152273992686998),
 (557, 0.07559289460184544),
 (558, 0.0),
 (559, 0.0),
 (560, 0.03162277660168379),
 (561, 0.05976143046671968),
 (562, 0.0),
 (563, 0.036760731104690386),
 (564, 0.05590169943749474),
 (565, 0.06201736729460423),
 (566, 0.035355339059327376),
 (567, 0.0),
 (568, 0.18257418583505539),
 (569, 0.035355339059327376),
 (570, 0.12403473458920845),
 (571, 0.03333333333333333),
 (572, 0.09302605094190634),
 (573, 0.03580574370197164),
 (574, 0.03261640365267211),
 (575, 0.03834824944236852),
 (576, 0.04152273992686998),
 (577, 0.13987572123604708),
 (578, 0.03261640365267211),
 (579, 0.05590169943749474),
 (580, 0.034099716973523674),
 (581, 0.18257418583505539),
 (582, 0.1267731382092775),
 (583, 0.07905694150420947),
 (584, 0.07905694150420947),
 (585, 0.0),
 (586, 0.06085806194501846),
 (587, 0.1556997888323046),
 (588, 0.036760731104690386),
 (589, 0.07453559924999298),
 (590, 0.04767312946227961),
 (591, 0.0816496580927726),
 (592, 0.03779644730092272),
 (593, 0.0),
 (594, 0.10846522890932808),
 (595, 0.10350983390135313),
 (596, 0.13333333333333333),
 (597, 0.09128709291752769),
 (598, 0.0),
 (599, 0.02439750182371333),
 (600, 0.06454972243679029),
 (601, 0.05096471914376255),
 (602, 0.06984302957695782),
 (603, 0.0816496580927726),
 (604, 0.09999999999999999),
 (605, 0.0),
 (606, 0.0),
 (607, 0.09128709291752768),
 (608, 0.0),
 (609, 0.03779644730092272),
 (610, 0.08195375470622296),
 (611, 0.03580574370197164),
 (612, 0.07071067811865475),
 (613, 0.0512989176042577),
 (614, 0.0512989176042577),
 (615, 0.04879500364742666),
 (616, 0.0),
 (617, 0.09759000729485331),
 (618, 0.15118578920369088),
 (619, 0.0),
 (620, 0.0),
 (621, 0.0512989176042577),
 (622, 0.03042903097250923),
 (623, 0.0),
 (624, 0.11952286093343936),
 (625, 0.0),
 (626, 0.1025978352085154),
 (627, 0.16770509831248423),
 (628, 0.0),
 (629, 0.03450327796711771),
 (630, 0.0),
 (631, 0.04016096644512494),
 (632, 0.07453559924999298),
 (633, 0.03261640365267211),
 (634, 0.14301938838683884),
 (635, 0.04016096644512494),
 (636, 0.043852900965351466),
 (637, 0.04662524041201569),
 (638, 0.0),
 (639, 0.0),
 (640, 0.07669649888473704),
 (641, 0.0),
 (642, 0.0),
 (643, 0.07559289460184544),
 (644, 0.08944271909999159),
 (645, 0.08304547985373996),
 (646, 0.0816496580927726),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.05976143046671968),
 (654, 0.13968605915391563),
 (655, 0.03627381250550058),
 (656, 0.0),
 (657, 0.05423261445466404),
 (658, 0.0778498944161523),
 (659, 0.04016096644512494),
 (660, 0.09759000729485331),
 (661, 0.09302605094190634),
 (662, 0.0),
 (663, 0.0),
 (664, 0.08606629658238704),
 (665, 0.07161148740394328),
 (666, 0.0),
 (667, 0.0),
 (668, 0.09759000729485331),
 (669, 0.0),
 (670, 0.0),
 (671, 0.03892494720807615),
 (672, 0.09999999999999999),
 (673, 0.03726779962499649),
 (674, 0.0659380473395787),
 (675, 0.07559289460184544),
 (676, 0.04662524041201569),
 (677, 0.05423261445466404),
 (678, 0.0816496580927726),
 (679, 0.0),
 (680, 0.03726779962499649),
 (681, 0.0),
 (682, 0.0),
 (683, 0.07352146220938077),
 (684, 0.0),
 (685, 0.05423261445466404),
 (686, 0.0),
 (687, 0.08304547985373996),
 (688, 0.0),
 (689, 0.0),
 (690, 0.04152273992686998),
 (691, 0.12909944487358058),
 (692, 0.0408248290463863),
 (693, 0.0),
 (694, 0.03627381250550058),
 (695, 0.11180339887498948),
 (696, 0.0),
 (697, 0.0),
 (698, 0.033709993123162106),
 (699, 0.0),
 (700, 0.049999999999999996),
 (701, 0.0),
 (702, 0.042257712736425826),
 (703, 0.0),
 (704, 0.043852900965351466),
 (705, 0.0),
 (706, 0.03779644730092272),
 (707, 0.0),
 (708, 0.043852900965351466),
 (709, 0.0),
 (710, 0.030714755841697562),
 (711, 0.09325048082403138),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (715, 0.15),
 (716, 0.045643546458763846),
 (717, 0.0),
 (718, 0.06523280730534423),
 (719, 0.0),
 (720, 0.043852900965351466),
 (721, 0.04767312946227961),
 (722, 0.0),
 (723, 0.03580574370197164),
 (724, 0.04152273992686998),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0512989176042577),
 (728, 0.11338934190276817),
 (729, 0.0),
 (730, 0.023063280200722125),
 (731, 0.08032193289024989),
 (732, 0.10741723110591492),
 (733, 0.0),
 (734, 0.07254762501100116),
 (735, 0.06984302957695782),
 (736, 0.0512989176042577),
 (737, 0.049999999999999996),
 (738, 0.0),
 (739, 0.05423261445466404),
 (740, 0.11338934190276817),
 (741, 0.08304547985373996),
 (742, 0.049999999999999996),
 (743, 0.03726779962499649),
 (744, 0.10540925533894599),
 (745, 0.08606629658238704),
 (746, 0.11858541225631421),
 (747, 0.031008683647302113),
 (748, 0.05590169943749474),
 (749, 0.0),
 (750, 0.0408248290463863),
 (751, 0.0),
 (752, 0.03834824944236852),
 (753, 0.04303314829119352),
 (754, 0.08770580193070293),
 (755, 0.09302605094190634),
 (756, 0.0),
 (757, 0.0),
 (758, 0.03580574370197164),
 (759, 0.0),
 (760, 0.0),
 (761, 0.04303314829119352),
 (762, 0.05590169943749474),
 (763, 0.0),
 (764, 0.042257712736425826),
 (765, 0.0),
 (766, 0.0),
 (767, 0.07559289460184544),
 (768, 0.09784921095801634),
 (769, 0.04662524041201569),
 (770, 0.03892494720807615),
 (771, 0.0),
 (772, 0.0),
 (773, 0.09999999999999999),
 (774, 0.06741998624632421),
 (775, 0.0816496580927726),
 (776, 0.05976143046671968),
 (777, 0.09682458365518543),
 (778, 0.09128709291752769),
 (779, 0.0),
 (780, 0.0),
 (781, 0.10846522890932808),
 (782, 0.10476454436543672),
 (783, 0.0512989176042577),
 (784, 0.13987572123604708),
 (785, 0.05345224838248488),
 (786, 0.11677484162422844),
 (787, 0.08032193289024989),
 (788, 0.07669649888473704),
 (789, 0.0),
 (790, 0.06666666666666667),
 (791, 0.049999999999999996),
 (792, 0.042257712736425826),
 (793, 0.039528470752104736),

In [62]:
sorted(list(enumerate(similarity[0])),reverse=True)

[(4805, 0.0),
 (4804, 0.0),
 (4803, 0.0),
 (4802, 0.0),
 (4801, 0.036760731104690386),
 (4800, 0.0),
 (4799, 0.08770580193070293),
 (4798, 0.03015113445777636),
 (4797, 0.0),
 (4796, 0.0),
 (4795, 0.0),
 (4794, 0.0),
 (4793, 0.0),
 (4792, 0.0),
 (4791, 0.0),
 (4790, 0.04152273992686998),
 (4789, 0.0),
 (4788, 0.0),
 (4787, 0.0),
 (4786, 0.0),
 (4785, 0.0),
 (4784, 0.0),
 (4783, 0.0),
 (4782, 0.0),
 (4781, 0.044721359549995794),
 (4780, 0.0),
 (4779, 0.0),
 (4778, 0.0),
 (4777, 0.0),
 (4776, 0.0),
 (4775, 0.043852900965351466),
 (4774, 0.0),
 (4773, 0.0),
 (4772, 0.03492151478847891),
 (4771, 0.0),
 (4770, 0.0),
 (4769, 0.0),
 (4768, 0.0),
 (4767, 0.0512989176042577),
 (4766, 0.0),
 (4765, 0.0),
 (4764, 0.0),
 (4763, 0.0),
 (4762, 0.0),
 (4761, 0.045643546458763846),
 (4760, 0.0),
 (4759, 0.035355339059327376),
 (4758, 0.0),
 (4757, 0.06454972243679029),
 (4756, 0.0),
 (4755, 0.0),
 (4754, 0.0),
 (4753, 0.0),
 (4752, 0.0),
 (4751, 0.0),
 (4750, 0.0),
 (4749, 0.0),
 (4748, 0.03726779962499649),
 (4747, 0.0),
 (4746, 0.0),
 (4745, 0.0),
 (4744, 0.0512989176042577),
 (4743, 0.0),
 (4742, 0.0),
 (4741, 0.0),
 (4740, 0.0),
 (4739, 0.0),
 (4738, 0.0),
 (4737, 0.11952286093343936),
 (4736, 0.0),
 (4735, 0.0),
 (4734, 0.0),
 (4733, 0.0),
 (4732, 0.0),
 (4731, 0.04767312946227961),
 (4730, 0.039528470752104736),
 (4729, 0.0),
 (4728, 0.0),
 (4727, 0.11547005383792514),
 (4726, 0.0),
 (4725, 0.0),
 (4724, 0.0),
 (4723, 0.0),
 (4722, 0.0),
 (4721, 0.0),
 (4720, 0.0),
 (4719, 0.0),
 (4718, 0.06741998624632421),
 (4717, 0.0),
 (4716, 0.0),
 (4715, 0.0),
 (4714, 0.0),
 (4713, 0.0),
 (4712, 0.0),
 (4711, 0.02711630722733202),
 (4710, 0.0),
 (4709, 0.0),
 (4708, 0.0),
 (4707, 0.0),
 (4706, 0.0),
 (4705, 0.0),
 (4704, 0.052704627669472995),
 (4703, 0.05773502691896257),
 (4702, 0.0),
 (4701, 0.0),
 (4700, 0.0),
 (4699, 0.0),
 (4698, 0.0),
 (4697, 0.0),
 (4696, 0.023186944788008413),
 (4695, 0.0),
 (4694, 0.03131121455425747),
 (4693, 0.04016096644512494),
 (4692, 0.0),
 (4691, 0.06454972243679029),
 (4690, 0.0),
 (4689, 0.0),
 (4688, 0.0),
 (4687, 0.0),
 (4686, 0.0),
 (4685, 0.0),
 (4684, 0.0),
 (4683, 0.0),
 (4682, 0.023836564731139806),
 (4681, 0.0),
 (4680, 0.0),
 (4679, 0.0),
 (4678, 0.0),
 (4677, 0.0),
 (4676, 0.0),
 (4675, 0.0),
 (4674, 0.0),
 (4673, 0.16269784336399212),
 (4672, 0.08032193289024989),
 (4671, 0.0),
 (4670, 0.0),
 (4669, 0.04662524041201569),
 (4668, 0.0),
 (4667, 0.04662524041201569),
 (4666, 0.0),
 (4665, 0.0),
 (4664, 0.0),
 (4663, 0.0),
 (4662, 0.0),
 (4661, 0.0),
 (4660, 0.0),
 (4659, 0.0),
 (4658, 0.0),
 (4657, 0.12048289933537483),
 (4656, 0.03015113445777636),
 (4655, 0.0),
 (4654, 0.06741998624632421),
 (4653, 0.0),
 (4652, 0.04879500364742666),
 (4651, 0.0),
 (4650, 0.0),
 (4649, 0.0),
 (4648, 0.0),
 (4647, 0.0),
 (4646, 0.0),
 (4645, 0.0),
 (4644, 0.0),
 (4643, 0.0),
 (4642, 0.06201736729460423),
 (4641, 0.12909944487358058),
 (4640, 0.04016096644512494),
 (4639, 0.0),
 (4638, 0.0),
 (4637, 0.0),
 (4636, 0.07905694150420947),
 (4635, 0.0),
 (4634, 0.0),
 (4633, 0.03492151478847891),
 (4632, 0.04879500364742666),
 (4631, 0.0),
 (4630, 0.0),
 (4629, 0.0),
 (4628, 0.0),
 (4627, 0.0),
 (4626, 0.08304547985373996),
 (4625, 0.0),
 (4624, 0.039528470752104736),
 (4623, 0.10540925533894599),
 (4622, 0.0),
 (4621, 0.0),
 (4620, 0.03779644730092272),
 (4619, 0.0),
 (4618, 0.0),
 (4617, 0.0),
 (4616, 0.0),
 (4615, 0.0),
 (4614, 0.0),
 (4613, 0.0),
 (4612, 0.0),
 (4611, 0.052704627669472995),
 (4610, 0.0),
 (4609, 0.0),
 (4608, 0.0),
 (4607, 0.0),
 (4606, 0.0),
 (4605, 0.0),
 (4604, 0.0512989176042577),
 (4603, 0.0),
 (4602, 0.08770580193070293),
 (4601, 0.0),
 (4600, 0.0),
 (4599, 0.0),
 (4598, 0.0),
 (4597, 0.0),
 (4596, 0.0),
 (4595, 0.0),
 (4594, 0.05976143046671968),
 (4593, 0.0),
 (4592, 0.0),
 (4591, 0.0),
 (4590, 0.042257712736425826),
 (4589, 0.0),
 (4588, 0.0),
 (4587, 0.0),
 (4586, 0.0),
 (4585, 0.0),
 (4584, 0.0),
 (4583, 0.0),
 (4582, 0.054635836470815304),
 (4581, 0.0),
 (4580, 0.0),
 (4579, 0.0),
 (4578, 0.0),
 (4577, 0.0),
 (4576, 0.0),
 (4575, 0.0),
 (4574, 0.0),
 (4573, 0.0),
 (4572, 0.0),
 (4571, 0.0),
 (4570, 0.0),
 (4569, 0.039528470752104736),
 (4568, 0.10846522890932808),
 (4567, 0.0),
 (4566, 0.10540925533894599),
 (4565, 0.020851441405707476),
 (4564, 0.05976143046671968),
 (4563, 0.0),
 (4562, 0.0),
 (4561, 0.0),
 (4560, 0.04303314829119352),
 (4559, 0.0),
 (4558, 0.0408248290463863),
 (4557, 0.05423261445466404),
 (4556, 0.0),
 (4555, 0.0),
 (4554, 0.0),
 (4553, 0.031943828249996996),
 (4552, 0.033709993123162106),
 (4551, 0.0),
 (4550, 0.0),
 (4549, 0.04016096644512494),
 (4548, 0.0),
 (4547, 0.0),
 (4546, 0.0),
 (4545, 0.06324555320336758),
 (4544, 0.0),
 (4543, 0.0),
 (4542, 0.06201736729460423),
 (4541, 0.0),
 (4540, 0.0),
 (4539, 0.0),
 (4538, 0.036760731104690386),
 (4537, 0.0),
 (4536, 0.0),
 (4535, 0.0),
 (4534, 0.0),
 (4533, 0.0),
 (4532, 0.0),
 (4531, 0.0),
 (4530, 0.0),
 (4529, 0.032274861218395144),
 (4528, 0.0),
 (4527, 0.0),
 (4526, 0.0),
 (4525, 0.0),
 (4524, 0.0),
 (4523, 0.0),
 (4522, 0.0),
 (4521, 0.0),
 (4520, 0.0),
 (4519, 0.09128709291752769),
 (4518, 0.0),
 (4517, 0.0),
 (4516, 0.07905694150420947),
 (4515, 0.0),
 (4514, 0.0),
 (4513, 0.0),
 (4512, 0.0),
 (4511, 0.0),
 (4510, 0.0),
 (4509, 0.0),
 (4508, 0.0),
 (4507, 0.0),
 (4506, 0.0),
 (4505, 0.0),
 (4504, 0.0),
 (4503, 0.0),
 (4502, 0.12909944487358058),
 (4501, 0.0),
 (4500, 0.0),
 (4499, 0.0),
 (4498, 0.0),
 (4497, 0.0),
 (4496, 0.0),
 (4495, 0.0),
 (4494, 0.0),
 (4493, 0.0),
 (4492, 0.05773502691896257),
 (4491, 0.0),
 (4490, 0.09128709291752769),
 (4489, 0.0),
 (4488, 0.0),
 (4487, 0.0),
 (4486, 0.0),
 (4485, 0.0),
 (4484, 0.03892494720807615),
 (4483, 0.0),
 (4482, 0.0),
 (4481, 0.0),
 (4480, 0.0),
 (4479, 0.0),
 (4478, 0.0),
 (4477, 0.0),
 (4476, 0.0),
 (4475, 0.0),
 (4474, 0.0),
 (4473, 0.05773502691896257),
 (4472, 0.05590169943749474),
 (4471, 0.0),
 (4470, 0.0),
 (4469, 0.03450327796711771),
 (4468, 0.09534625892455922),
 (4467, 0.0),
 (4466, 0.03131121455425747),
 (4465, 0.0),
 (4464, 0.0),
 (4463, 0.05773502691896257),
 (4462, 0.0),
 (4461, 0.0),
 (4460, 0.0),
 (4459, 0.0),
 (4458, 0.0),
 (4457, 0.0),
 (4456, 0.0),
 (4455, 0.0),
 (4454, 0.0),
 (4453, 0.07071067811865475),
 (4452, 0.0),
 (4451, 0.036760731104690386),
 (4450, 0.0),
 (4449, 0.0),
 (4448, 0.0),
 (4447, 0.0),
 (4446, 0.0),
 (4445, 0.0),
 (4444, 0.0),
 (4443, 0.05976143046671968),
 (4442, 0.0),
 (4441, 0.0),
 (4440, 0.0),
 (4439, 0.0),
 (4438, 0.0),
 (4437, 0.0),
 (4436, 0.0),
 (4435, 0.0),
 (4434, 0.0),
 (4433, 0.0),
 (4432, 0.0),
 (4431, 0.07453559924999298),
 (4430, 0.0),
 (4429, 0.06201736729460423),
 (4428, 0.0),
 (4427, 0.039528470752104736),
 (4426, 0.0),
 (4425, 0.0),
 (4424, 0.0),
 (4423, 0.0),
 (4422, 0.0),
 (4421, 0.0),
 (4420, 0.0),
 (4419, 0.0),
 (4418, 0.0),
 (4417, 0.0),
 (4416, 0.0),
 (4415, 0.0),
 (4414, 0.0),
 (4413, 0.0),
 (4412, 0.06454972243679029),
 (4411, 0.0),
 (4410, 0.0),
 (4409, 0.0),
 (4408, 0.0),
 (4407, 0.0),
 (4406, 0.043852900965351466),
 (4405, 0.25819888974716115),
 (4404, 0.0),
 (4403, 0.11952286093343936),
 (4402, 0.043852900965351466),
 (4401, 0.0),
 (4400, 0.0),
 (4399, 0.06741998624632421),
 (4398, 0.0),
 (4397, 0.0),
 (4396, 0.0),
 (4395, 0.0),
 (4394, 0.0),
 (4393, 0.0),
 (4392, 0.03492151478847891),
 (4391, 0.0),
 (4390, 0.05423261445466404),
 (4389, 0.0),
 (4388, 0.0),
 (4387, 0.0),
 (4386, 0.0),
 (4385, 0.0),
 (4384, 0.0),
 (4383, 0.03627381250550058),
 (4382, 0.036760731104690386),
 (4381, 0.0),
 (4380, 0.0408248290463863),
 (4379, 0.0),
 (4378, 0.0),
 (4377, 0.0),
 (4376, 0.0),
 (4375, 0.0),
 (4374, 0.0),
 (4373, 0.0),
 (4372, 0.03627381250550058),
 (4371, 0.0),
 (4370, 0.0),
 (4369, 0.0),
 (4368, 0.0),
 (4367, 0.0),
 (4366, 0.0),
 (4365, 0.0),
 (4364, 0.0),
 (4363, 0.0),
 (4362, 0.0),
 (4361, 0.0),
 (4360, 0.0),
 (4359, 0.0),
 (4358, 0.0),
 (4357, 0.1025978352085154),
 (4356, 0.0),
 (4355, 0.09534625892455922),
 (4354, 0.0),
 (4353, 0.06454972243679029),
 (4352, 0.0),
 (4351, 0.05976143046671968),
 (4350, 0.0),
 (4349, 0.0),
 (4348, 0.22360679774997894),
 (4347, 0.0),
 (4346, 0.0),
 (4345, 0.0),
 (4344, 0.0),
 (4343, 0.0778498944161523),
 (4342, 0.0),
 (4341, 0.045643546458763846),
 (4340, 0.0),
 (4339, 0.04016096644512494),
 (4338, 0.0),
 (4337, 0.0),
 (4336, 0.08032193289024989),
 (4335, 0.0),
 (4334, 0.0),
 (4333, 0.0),
 (4332, 0.052704627669472995),
 (4331, 0.10540925533894599),
 (4330, 0.054635836470815304),
 (4329, 0.07905694150420947),
 (4328, 0.0),
 (4327, 0.043852900965351466),
 (4326, 0.0),
 (4325, 0.0),
 (4324, 0.0),
 (4323, 0.0),
 (4322, 0.0),
 (4321, 0.0),
 (4320, 0.08606629658238704),
 (4319, 0.04662524041201569),
 (4318, 0.0),
 (4317, 0.036760731104690386),
 (4316, 0.1025978352085154),
 (4315, 0.0),
 (4314, 0.054635836470815304),
 (4313, 0.045643546458763846),
 (4312, 0.0),
 (4311, 0.0),
 (4310, 0.0),
 (4309, 0.0),
 (4308, 0.0),
 (4307, 0.0),
 (4306, 0.0),
 (4305, 0.08588975014708022),
 (4304, 0.0),
 (4303, 0.0),
 (4302, 0.0),
 (4301, 0.0),
 (4300, 0.0),
 (4299, 0.0),
 (4298, 0.0),
 (4297, 0.0),
 (4296, 0.0),
 (4295, 0.0),
 (4294, 0.0),
 (4293, 0.0),
 (4292, 0.044721359549995794),
 (4291, 0.0),
 (4290, 0.09534625892455922),
 (4289, 0.0),
 (4288, 0.044721359549995794),
 (4287, 0.0),
 (4286, 0.0),
 (4285, 0.0),
 (4284, 0.0),
 (4283, 0.0),
 (4282, 0.0),
 (4281, 0.07071067811865475),
 (4280, 0.03261640365267211),
 (4279, 0.06454972243679029),
 (4278, 0.0),
 (4277, 0.02564945880212885),
 (4276, 0.0),
 (4275, 0.0),
 (4274, 0.0),
 (4273, 0.0),
 (4272, 0.0),
 (4271, 0.1025978352085154),
 (4270, 0.09325048082403138),
 (4269, 0.0),
 (4268, 0.0),
 (4267, 0.0),
 (4266, 0.036760731104690386),
 (4265, 0.02795084971874737),
 (4264, 0.0),
 (4263, 0.03779644730092272),
 (4262, 0.0408248290463863),
 (4261, 0.03492151478847891),
 (4260, 0.0),
 (4259, 0.06454972243679029),
 (4258, 0.0),
 (4257, 0.0512989176042577),
 (4256, 0.0),
 (4255, 0.0),
 (4254, 0.09325048082403138),
 (4253, 0.0),
 (4252, 0.0),
 (4251, 0.0),
 (4250, 0.0),
 (4249, 0.0),
 (4248, 0.042257712736425826),
 (4247, 0.0),
 (4246, 0.0),
 (4245, 0.0),
 (4244, 0.0),
 (4243, 0.0),
 (4242, 0.0),
 (4241, 0.0),
 (4240, 0.0),
 (4239, 0.0),
 (4238, 0.0),
 (4237, 0.0),
 (4236, 0.03726779962499649),
 (4235, 0.0),
 (4234, 0.0),
 (4233, 0.03296902366978935),
 (4232, 0.0),
 (4231, 0.0),
 (4230, 0.0),
 (4229, 0.0),
 (4228, 0.0512989176042577),
 (4227, 0.0),
 (4226, 0.0),
 (4225, 0.0),
 (4224, 0.0),
 (4223, 0.02103515809558356),
 (4222, 0.0),
 (4221, 0.0),
 (4220, 0.0),
 (4219, 0.0),
 (4218, 0.0512989176042577),
 (4217, 0.0),
 (4216, 0.0),
 (4215, 0.0),
 (4214, 0.05423261445466404),
 (4213, 0.0),
 (4212, 0.0),
 (4211, 0.0),
 (4210, 0.0),
 (4209, 0.0),
 (4208, 0.0),
 (4207, 0.0),
 (4206, 0.0),
 (4205, 0.0),
 (4204, 0.0),
 (4203, 0.0),
 (4202, 0.0),
 (4201, 0.09759000729485331),
 (4200, 0.0),
 (4199, 0.0),
 (4198, 0.0),
 (4197, 0.0),
 (4196, 0.11547005383792514),
 (4195, 0.0),
 (4194, 0.09759000729485331),
 (4193, 0.0),
 (4192, 0.0408248290463863),
 (4191, 0.0),
 (4190, 0.16770509831248423),
 (4189, 0.0),
 (4188, 0.0),
 (4187, 0.0),
 (4186, 0.0),
 (4185, 0.03779644730092272),
 (4184, 0.0),
 (4183, 0.0),
 (4182, 0.0),
 (4181, 0.0),
 (4180, 0.0),
 (4179, 0.10112997936948631),
 (4178, 0.036760731104690386),
 (4177, 0.0),
 (4176, 0.0),
 (4175, 0.0),
 (4174, 0.0),
 (4173, 0.0),
 (4172, 0.0),
 (4171, 0.0),
 (4170, 0.0),
 (4169, 0.0),
 (4168, 0.0),
 (4167, 0.02795084971874737),
 (4166, 0.0),
 (4165, 0.0),
 (4164, 0.04303314829119352),
 (4163, 0.10540925533894599),
 (4162, 0.0),
 (4161, 0.0),
 (4160, 0.0),
 (4159, 0.026171196129510684),
 (4158, 0.061429511683395124),
 (4157, 0.0),
 (4156, 0.0),
 (4155, 0.0),
 (4154, 0.0),
 (4153, 0.0),
 (4152, 0.03015113445777636),
 (4151, 0.0),
 (4150, 0.0),
 (4149, 0.03834824944236852),
 (4148, 0.0),
 (4147, 0.0),
 (4146, 0.08606629658238704),
 (4145, 0.0),
 (4144, 0.0),
 (4143, 0.0),
 (4142, 0.0),
 (4141, 0.0),
 (4140, 0.0),
 (4139, 0.04662524041201569),
 (4138, 0.0),
 (4137, 0.0),
 (4136, 0.0),
 (4135, 0.05590169943749474),
 (4134, 0.0),
 (4133, 0.10540925533894599),
 (4132, 0.044721359549995794),
 (4131, 0.0),
 (4130, 0.0),
 (4129, 0.05590169943749474),
 (4128, 0.052704627669472995),
 (4127, 0.022941573387056175),
 (4126, 0.0),
 (4125, 0.0),
 (4124, 0.0),
 (4123, 0.0408248290463863),
 (4122, 0.0),
 (4121, 0.10350983390135313),
 (4120, 0.0),
 (4119, 0.0),
 (4118, 0.02936101097573517),
 (4117, 0.04662524041201569),
 (4116, 0.0),
 (4115, 0.028867513459481284),
 (4114, 0.0),
 (4113, 0.0),
 (4112, 0.0),
 (4111, 0.0),
 (4110, 0.045643546458763846),
 (4109, 0.0),
 (4108, 0.0),
 (4107, 0.0),
 (4106, 0.0),
 (4105, 0.0),
 (4104, 0.0),
 (4103, 0.032274861218395144),
 (4102, 0.0),
 (4101, 0.0),
 (4100, 0.0),
 (4099, 0.0),
 (4098, 0.0),
 (4097, 0.11180339887498948),
 (4096, 0.0),
 (4095, 0.0),
 (4094, 0.0),
 (4093, 0.0),
 (4092, 0.0),
 (4091, 0.0),
 (4090, 0.0),
 (4089, 0.049999999999999996),
 (4088, 0.049999999999999996),
 (4087, 0.0),
 (4086, 0.0),
 (4085, 0.0),
 (4084, 0.0),
 (4083, 0.0),
 (4082, 0.04016096644512494),
 (4081, 0.14301938838683884),
 (4080, 0.0),
 (4079, 0.0),
 (4078, 0.04016096644512494),
 (4077, 0.045643546458763846),
 (4076, 0.044721359549995794),
 (4075, 0.06666666666666667),
 (4074, 0.05423261445466404),
 (4073, 0.06201736729460423),
 (4072, 0.0),
 (4071, 0.0),
 (4070, 0.0),
 (4069, 0.0),
 (4068, 0.0),
 (4067, 0.0),
 (4066, 0.0),
 (4065, 0.035355339059327376),
 (4064, 0.0),
 (4063, 0.0),
 (4062, 0.0),
 (4061, 0.034099716973523674),
 (4060, 0.0),
 (4059, 0.11180339887498948),
 (4058, 0.0),
 (4057, 0.0),
 (4056, 0.0),
 (4055, 0.0),
 (4054, 0.0),
 (4053, 0.12048289933537483),
 (4052, 0.0),
 (4051, 0.0),
 (4050, 0.0),
 (4049, 0.030714755841697562),
 (4048, 0.0),
 (4047, 0.0),
 (4046, 0.20377787840885372),
 (4045, 0.0),
 (4044, 0.0),
 (4043, 0.13987572123604708),
 (4042, 0.05423261445466404),
 (4041, 0.0),
 (4040, 0.0),
 (4039, 0.0),
 (4038, 0.0),
 (4037, 0.05423261445466404),
 (4036, 0.04767312946227961),
 (4035, 0.0),
 (4034, 0.0),
 (4033, 0.0),
 (4032, 0.0),
 (4031, 0.0),
 (4030, 0.0),
 (4029, 0.0),
 (4028, 0.0),
 (4027, 0.0),
 (4026, 0.027524094128159014),
 (4025, 0.0),
 (4024, 0.0),
 (4023, 0.0),
 (4022, 0.0),
 (4021, 0.0),
 (4020, 0.0),
 (4019, 0.0),
 (4018, 0.0),
 (4017, 0.025482359571881275),
 (4016, 0.11952286093343936),
 (4015, 0.034099716973523674),
 (4014, 0.0),
 (4013, 0.0),
 (4012, 0.0),
 (4011, 0.03450327796711771),
 (4010, 0.0),
 (4009, 0.0),
 (4008, 0.21693045781865616),
 (4007, 0.05590169943749474),
 (4006, 0.0),
 (4005, 0.0),
 (4004, 0.0),
 (4003, 0.0),
 (4002, 0.0),
 (4001, 0.0),
 (4000, 0.0),
 (3999, 0.0),
 (3998, 0.05976143046671968),
 (3997, 0.17888543819998318),
 (3996, 0.0),
 (3995, 0.03779644730092272),
 (3994, 0.0),
 (3993, 0.0),
 (3992, 0.10540925533894599),
 (3991, 0.035355339059327376),
 (3990, 0.08606629658238704),
 (3989, 0.0),
 (3988, 0.0),
 (3987, 0.0),
 (3986, 0.05976143046671968),
 (3985, 0.0),
 (3984, 0.0),
 (3983, 0.0),
 (3982, 0.0),
 (3981, 0.0),
 (3980, 0.0512989176042577),
 (3979, 0.0),
 (3978, 0.0),
 (3977, 0.0),
 (3976, 0.06201736729460423),
 (3975, 0.042257712736425826),
 (3974, 0.05976143046671968),
 (3973, 0.0),
 (3972, 0.0),
 (3971, 0.0),
 (3970, 0.05423261445466404),
 (3969, 0.05976143046671968),
 (3968, 0.0),
 (3967, 0.0),
 (3966, 0.049999999999999996),
 (3965, 0.0),
 (3964, 0.0),
 (3963, 0.0),
 (3962, 0.0),
 (3961, 0.0),
 (3960, 0.06201736729460423),
 (3959, 0.0),
 (3958, 0.0),
 (3957, 0.0),
 (3956, 0.0),
 (3955, 0.0),
 (3954, 0.0),
 (3953, 0.0),
 (3952, 0.09759000729485331),
 (3951, 0.0),
 (3950, 0.0),
 (3949, 0.044721359549995794),
 (3948, 0.03296902366978935),
 (3947, 0.06201736729460423),
 (3946, 0.02773500981126146),
 (3945, 0.034099716973523674),
 (3944, 0.05773502691896257),
 (3943, 0.0),
 (3942, 0.0),
 (3941, 0.0),
 (3940, 0.0),
 (3939, 0.0),
 (3938, 0.0),
 (3937, 0.0),
 (3936, 0.0),
 (3935, 0.043852900965351466),
 (3934, 0.0),
 (3933, 0.08451542547285165),
 (3932, 0.049999999999999996),
 (3931, 0.0),
 (3930, 0.0),
 (3929, 0.0),
 (3928, 0.0),
 (3927, 0.0),
 (3926, 0.0),
 (3925, 0.0),
 (3924, 0.08451542547285165),
 (3923, 0.039528470752104736),
 (3922, 0.0),
 (3921, 0.0),
 (3920, 0.0),
 (3919, 0.0),
 (3918, 0.0),
 (3917, 0.0),
 (3916, 0.05423261445466404),
 (3915, 0.0),
 (3914, 0.0),
 (3913, 0.0),
 (3912, 0.05976143046671968),
 (3911, 0.03162277660168379),
 (3910, 0.0),
 (3909, 0.0),
 (3908, 0.03892494720807615),
 (3907, 0.0),
 (3906, 0.0),
 (3905, 0.11180339887498947),
 (3904, 0.0),
 (3903, 0.061429511683395124),
 (3902, 0.0),
 (3901, 0.0),
 (3900, 0.0),
 (3899, 0.04879500364742666),
 (3898, 0.0),
 (3897, 0.0),
 (3896, 0.0),
 (3895, 0.0),
 (3894, 0.0),
 (3893, 0.0),
 (3892, 0.0),
 (3891, 0.0),
 (3890, 0.02862991671569341),
 (3889, 0.05976143046671968),
 (3888, 0.08944271909999159),
 (3887, 0.0),
 (3886, 0.07453559924999298),
 (3885, 0.0),
 (3884, 0.0),
 (3883, 0.0),
 (3882, 0.0),
 (3881, 0.0),
 (3880, 0.0),
 (3879, 0.03296902366978935),
 (3878, 0.0),
 (3877, 0.039528470752104736),
 (3876, 0.0),
 (3875, 0.0),
 (3874, 0.0),
 (3873, 0.0),
 (3872, 0.03834824944236852),
 (3871, 0.0),
 (3870, 0.0),
 (3869, 0.0),
 (3868, 0.0),
 (3867, 0.0),
 (3866, 0.0),
 (3865, 0.0),
 (3864, 0.0),
 (3863, 0.0),
 (3862, 0.0),
 (3861, 0.04879500364742666),
 (3860, 0.08519427513705971),
 (3859, 0.0),
 (3858, 0.04767312946227961),
 (3857, 0.0),
 (3856, 0.0),
 (3855, 0.044721359549995794),
 (3854, 0.0),
 (3853, 0.0408248290463863),
 (3852, 0.07071067811865475),
 (3851, 0.0),
 (3850, 0.0),
 (3849, 0.045643546458763846),
 (3848, 0.0),
 (3847, 0.0),
 (3846, 0.0408248290463863),
 (3845, 0.04303314829119352),
 (3844, 0.0),
 (3843, 0.0),
 (3842, 0.0),
 (3841, 0.0),
 (3840, 0.05423261445466404),
 (3839, 0.0),
 (3838, 0.0),
 (3837, 0.09534625892455922),
 (3836, 0.0),
 (3835, 0.0),
 (3834, 0.03892494720807615),
 (3833, 0.0),
 (3832, 0.049999999999999996),
 (3831, 0.0),
 (3830, 0.11547005383792514),
 (3829, 0.0),
 (3828, 0.0),
 (3827, 0.0),
 (3826, 0.0),
 (3825, 0.0),
 (3824, 0.0),
 (3823, 0.035355339059327376),
 (3822, 0.0),
 (3821, 0.0),
 (3820, 0.03450327796711771),
 (3819, 0.0),
 (3818, 0.0),
 (3817, 0.0),
 (3816, 0.0),
 (3815, 0.0),
 (3814, 0.043852900965351466),
 (3813, 0.0),
 (3812, 0.0),
 (3811, 0.0),
 (3810, 0.0),
 (3809, 0.0),
 (3808, 0.0657793514480272),
 (3807, 0.0),
 (3806, 0.0),
 ...]

In [63]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 1.0000000000000002),
 (151, 0.26967994498529685),
 (4405, 0.25819888974716115),
 (942, 0.24913643956121986),
 (1440, 0.2480694691784169),
 (1192, 0.2439750182371333),
 (3606, 0.24152294576982397),
 (495, 0.22360679774997896),
 (4348, 0.22360679774997894),
 (7, 0.22056438662814232),
 (972, 0.21926450482675733),
 (31, 0.21693045781865616),
 (94, 0.21693045781865616),
 (4008, 0.21693045781865616),
 (2997, 0.21213203435596426),
 (3728, 0.21213203435596426),
 (973, 0.2076136996343499),
 (1214, 0.20732210721568234),
 (61, 0.2051956704170308),
 (68, 0.2051956704170308),
 (322, 0.2051956704170308),
 (1342, 0.20412414523193148),
 (4046, 0.20377787840885372),
 (208, 0.20225995873897262),
 (199, 0.20080483222562473),
 (466, 0.19999999999999998),
 (36, 0.1976423537605237),
 (232, 0.19518001458970663),
 (483, 0.19518001458970663),
 (1612, 0.19518001458970663),
 (83, 0.19364916731037088),
 (1654, 0.19069251784911845),
 (1392, 0.1889822365046136),
 (1804, 0.1889822365046136),
 (2405, 0.1889822365046136),
 (72, 0.18650096164806276),
 (539, 0.18650096164806276),
 (2969, 0.18428853505018536),
 (26, 0.18257418583505539),
 (46, 0.18257418583505539),
 (150, 0.18257418583505539),
 (568, 0.18257418583505539),
 (581, 0.18257418583505539),
 (931, 0.18257418583505539),
 (420, 0.1813690625275029),
 (35, 0.17928429140015906),
 (1199, 0.17928429140015906),
 (2071, 0.17888543819998318),
 (3338, 0.17888543819998318),
 (3997, 0.17888543819998318),
 (149, 0.17677669529663687),
 (507, 0.17677669529663687),
 (2329, 0.17677669529663687),
 (174, 0.17541160386140586),
 (28, 0.1732050807568877),
 (490, 0.1732050807568877),
 (14, 0.17213259316477408),
 (2165, 0.17213259316477408),
 (3496, 0.17213259316477408),
 (3620, 0.17213259316477408),
 (529, 0.16854996561581054),
 (127, 0.16770509831248423),
 (134, 0.16770509831248423),
 (487, 0.16770509831248423),
 (627, 0.16770509831248423),
 (1327, 0.16770509831248423),
 (1484, 0.16770509831248423),
 (2782, 0.16770509831248423),
 (4190, 0.16770509831248423),
 (91, 0.16609095970747992),
 (813, 0.16609095970747992),
 (1035, 0.16609095970747992),
 (1202, 0.16609095970747992),
 (1295, 0.16609095970747992),
 (1275, 0.16484511834894675),
 (10, 0.1632993161855452),
 (1916, 0.1632993161855452),
 (2068, 0.1632993161855452),
 (12, 0.16269784336399212),
 (98, 0.16269784336399212),
 (330, 0.16269784336399212),
 (505, 0.16269784336399212),
 (2580, 0.16269784336399212),
 (2647, 0.16269784336399212),
 (3352, 0.16269784336399212),
 (3719, 0.16269784336399212),
 (4673, 0.16269784336399212),
 (27, 0.16137430609197573),
 (206, 0.16137430609197573),
 (311, 0.16064386578049977),
 (508, 0.16064386578049977),
 (859, 0.16064386578049977),
 (1193, 0.16064386578049977),
 (3441, 0.16064386578049977),
 (403, 0.15971914124998499),
 (3405, 0.15971914124998499),
 (33, 0.158113883008419),
 (56, 0.158113883008419),
 (122, 0.158113883008419),
 (233, 0.158113883008419),
 (1107, 0.158113883008419),
 (1520, 0.158113883008419),
 (2657, 0.158113883008419),
 (1297, 0.15811388300841894),
 (1941, 0.15811388300841894),
 (47, 0.15655607277128736),
 (74, 0.1556997888323046),
 (587, 0.1556997888323046),
 (1, 0.1538967528127731),
 (148, 0.1538967528127731),
 (260, 0.1538967528127731),
 (292, 0.1538967528127731),
 (794, 0.1538967528127731),
 (1404, 0.1538967528127731),
 (2492, 0.1538967528127731),
 (3053, 0.1538967528127731),
 (84, 0.1535737792084878),
 (5, 0.15339299776947407),
 (43, 0.15339299776947407),
 (139, 0.15339299776947407),
 (187, 0.15339299776947407),
 (986, 0.15339299776947407),
 (1533, 0.15339299776947407),
 (1827, 0.15339299776947407),
 (1961, 0.15214515486254615),
 (168, 0.15118578920369088),
 (618, 0.15118578920369088),
 (2682, 0.15118578920369088),
 (23, 0.15),
 (263, 0.15),
 (275, 0.15),
 (400, 0.15),
 (715, 0.15),
 (1938, 0.15),
 (2319, 0.15),
 (158, 0.14907119849998596),
 (870, 0.14907119849998596),
 (1231, 0.14907119849998596),
 (2129, 0.14907119849998596),
 (3152, 0.14907119849998596),
 (131, 0.14704292441876154),
 (138, 0.14638501094227996),
 (166, 0.14638501094227996),
 (511, 0.14638501094227996),
 (922, 0.14638501094227996),
 (1075, 0.14638501094227996),
 (1080, 0.14638501094227996),
 (1299, 0.14638501094227996),
 (1829, 0.14638501094227996),
 (3353, 0.14638501094227996),
 (312, 0.14509525002200233),
 (2592, 0.14509525002200233),
 (3160, 0.14509525002200233),
 (461, 0.14301938838683884),
 (634, 0.14301938838683884),
 (1045, 0.14301938838683884),
 (1069, 0.14301938838683884),
 (1156, 0.14301938838683884),
 (1585, 0.14301938838683884),
 (1752, 0.14301938838683884),
 (2679, 0.14301938838683884),
 (2813, 0.14301938838683884),
 (4081, 0.14301938838683884),
 (200, 0.1414213562373095),
 (228, 0.1414213562373095),
 (123, 0.13987572123604708),
 (577, 0.13987572123604708),
 (784, 0.13987572123604708),
 (920, 0.13987572123604708),
 (1272, 0.13987572123604708),
 (1278, 0.13987572123604708),
 (4043, 0.13987572123604708),
 (654, 0.13968605915391563),
 (17, 0.13801311186847084),
 (1934, 0.13801311186847084),
 (207, 0.13693063937629155),
 (242, 0.13693063937629155),
 (329, 0.13693063937629155),
 (978, 0.13693063937629155),
 (2374, 0.13693063937629155),
 (2864, 0.13693063937629155),
 (2102, 0.1363988678940947),
 (2444, 0.1363988678940947),
 (256, 0.13483997249264842),
 (412, 0.13483997249264842),
 (838, 0.13483997249264842),
 (1274, 0.13483997249264842),
 (3570, 0.13483997249264842),
 (349, 0.1341640786499874),
 (854, 0.1341640786499874),
 (899, 0.1341640786499874),
 (1094, 0.1341640786499874),
 (1111, 0.1341640786499874),
 (1140, 0.1341640786499874),
 (1273, 0.1341640786499874),
 (2200, 0.1341640786499874),
 (2392, 0.1341640786499874),
 (2616, 0.1341640786499874),
 (596, 0.13333333333333333),
 (107, 0.1318760946791574),
 (87, 0.1315587028960544),
 (101, 0.1315587028960544),
 (203, 0.1315587028960544),
 (1304, 0.1315587028960544),
 (1379, 0.1315587028960544),
 (62, 0.12909944487358058),
 (109, 0.12909944487358058),
 (422, 0.12909944487358058),
 (691, 0.12909944487358058),
 (1319, 0.12909944487358058),
 (1406, 0.12909944487358058),
 (1660, 0.12909944487358058),
 (1669, 0.12909944487358058),
 (2384, 0.12909944487358058),
 (2630, 0.12909944487358058),
 (4502, 0.12909944487358058),
 (4641, 0.12909944487358058),
 (39, 0.12909944487358055),
 (52, 0.12909944487358055),
 (96, 0.12909944487358055),
 (111, 0.12909944487358055),
 (1002, 0.12909944487358055),
 (1084, 0.12909944487358055),
 (2446, 0.12909944487358055),
 (1635, 0.12777531299998798),
 (270, 0.1267731382092775),
 (300, 0.1267731382092775),
 (315, 0.1267731382092775),
 (332, 0.1267731382092775),
 (369, 0.1267731382092775),
 (582, 0.1267731382092775),
 (894, 0.1267731382092775),
 (960, 0.1267731382092775),
 (1013, 0.1267731382092775),
 (1017, 0.12649110640673517),
 (45, 0.12524485821702988),
 (467, 0.12524485821702988),
 (50, 0.12456821978060995),
 (121, 0.12456821978060995),
 (1267, 0.12456821978060995),
 (2368, 0.12456821978060995),
 (3006, 0.12456821978060995),
 (381, 0.12403473458920845),
 (570, 0.12403473458920845),
 (1137, 0.12403473458920845),
 (1617, 0.12403473458920845),
 (2246, 0.12403473458920845),
 (2270, 0.12403473458920845),
 (2852, 0.12403473458920845),
 (3153, 0.12403473458920845),
 (1530, 0.12285902336679025),
 (16, 0.1224744871391589),
 (241, 0.1224744871391589),
 (1176, 0.1224744871391589),
 (2159, 0.1224744871391589),
 (2827, 0.1224744871391589),
 (3426, 0.1224744871391589),
 (238, 0.12171612389003691),
 (1280, 0.12171612389003691),
 (102, 0.12060453783110545),
 (4, 0.12048289933537483),
 (67, 0.12048289933537483),
 (76, 0.12048289933537483),
 (215, 0.12048289933537483),
 (1159, 0.12048289933537483),
 (1397, 0.12048289933537483),
 (1978, 0.12048289933537483),
 (4053, 0.12048289933537483),
 (4657, 0.12048289933537483),
 (172, 0.11952286093343936),
 (230, 0.11952286093343936),
 (624, 0.11952286093343936),
 (808, 0.11952286093343936),
 (850, 0.11952286093343936),
 (1154, 0.11952286093343936),
 (2377, 0.11952286093343936),
 (2641, 0.11952286093343936),
 (3372, 0.11952286093343936),
 (3779, 0.11952286093343936),
 (4016, 0.11952286093343936),
 (4403, 0.11952286093343936),
 (4737, 0.11952286093343936),
 (126, 0.11858541225631421),
 (164, 0.11858541225631421),
 (182, 0.11858541225631421),
 (262, 0.11858541225631421),
 (271, 0.11858541225631421),
 (513, 0.11858541225631421),
 (746, 0.11858541225631421),
 (1028, 0.11858541225631421),
 (1619, 0.11858541225631421),
 (2914, 0.11858541225631421),
 (939, 0.11744404390294068),
 (2009, 0.11677484162422845),
 (212, 0.11677484162422844),
 (243, 0.11677484162422844),
 (786, 0.11677484162422844),
 (1613, 0.11677484162422844),
 (1628, 0.11677484162422844),
 (105, 0.11547005383792514),
 (249, 0.11547005383792514),
 (373, 0.11547005383792514),
 (1321, 0.11547005383792514),
 (1717, 0.11547005383792514),
 (1723, 0.11547005383792514),
 (2132, 0.11547005383792514),
 (2476, 0.11547005383792514),
 (2511, 0.11547005383792514),
 (3830, 0.11547005383792514),
 (4196, 0.11547005383792514),
 (4727, 0.11547005383792514),
 (278, 0.11504474832710555),
 (334, 0.11504474832710555),
 (413, 0.11504474832710555),
 (472, 0.11504474832710555),
 (473, 0.11504474832710555),
 (985, 0.11504474832710555),
 (1218, 0.11504474832710555),
 (2816, 0.11504474832710555),
 (3089, 0.11504474832710555),
 (3307, 0.11504474832710555),
 (1894, 0.11451966686277364),
 (11, 0.11338934190276817),
 (79, 0.11338934190276817),
 (108, 0.11338934190276817),
 (728, 0.11338934190276817),
 (740, 0.11338934190276817),
 (3308, 0.11338934190276817),
 (3618, 0.11338934190276817),
 (159, 0.11180339887498948),
 (216, 0.11180339887498948),
 (547, 0.11180339887498948),
 (695, 0.11180339887498948),
 (823, 0.11180339887498948),
 (1090, 0.11180339887498948),
 (1369, 0.11180339887498948),
 (1737, 0.11180339887498948),
 (2157, 0.11180339887498948),
 (2255, 0.11180339887498948),
 (2322, 0.11180339887498948),
 (3070, 0.11180339887498948),
 (3251, 0.11180339887498948),
 (3525, 0.11180339887498948),
 (3619, 0.11180339887498948),
 (4059, 0.11180339887498948),
 (4097, 0.11180339887498948),
 (9, 0.11180339887498947),
 (70, 0.11180339887498947),
 (213, 0.11180339887498947),
 (279, 0.11180339887498947),
 (305, 0.11180339887498947),
 (1992, 0.11180339887498947),
 (2579, 0.11180339887498947),
 (3100, 0.11180339887498947),
 (3905, 0.11180339887498947),
 (19, 0.11028219331407116),
 (30, 0.11028219331407116),
 (184, 0.11028219331407116),
 (535, 0.11028219331407116),
 (933, 0.11028219331407116),
 (1173, 0.11028219331407116),
 (1271, 0.11028219331407116),
 (342, 0.10927167294163061),
 (71, 0.10882143751650175),
 (169, 0.10882143751650175),
 (977, 0.10882143751650175),
 (1054, 0.10882143751650175),
 (1200, 0.10882143751650175),
 (22, 0.10846522890932808),
 (267, 0.10846522890932808),
 (537, 0.10846522890932808),
 (594, 0.10846522890932808),
 (781, 0.10846522890932808),
 (935, 0.10846522890932808),
 (1071, 0.10846522890932808),
 (1074, 0.10846522890932808),
 (1240, 0.10846522890932808),
 (1332, 0.10846522890932808),
 (1361, 0.10846522890932808),
 (1497, 0.10846522890932808),
 (2266, 0.10846522890932808),
 (2880, 0.10846522890932808),
 (2968, 0.10846522890932808),
 (3354, 0.10846522890932808),
 (4568, 0.10846522890932808),
 (1363, 0.10741723110591493),
 (97, 0.10741723110591492),
 (234, 0.10741723110591492),
 (732, 0.10741723110591492),
 (1189, 0.10741723110591492),
 (1276, 0.10741723110591492),
 (2048, 0.10741723110591492),
 (2260, 0.10741723110591492),
 (410, 0.10606601717798213),
 (419, 0.10606601717798213),
 (1303, 0.10606601717798213),
 (1492, 0.10606601717798213),
 (1655, 0.10606601717798213),
 (3223, 0.10606601717798213),
 (3388, 0.10606601717798213),
 (117, 0.10540925533894599),
 (157, 0.10540925533894599),
 (205, 0.10540925533894599),
 (744, 0.10540925533894599),
 (800, 0.10540925533894599),
 (1003, 0.10540925533894599),
 (1096, 0.10540925533894599),
 (1145, 0.10540925533894599),
 (1286, 0.10540925533894599),
 (1290, 0.10540925533894599),
 (1470, 0.10540925533894599),
 (1571, 0.10540925533894599),
 (2727, 0.10540925533894599),
 (3992, 0.10540925533894599),
 (4133, 0.10540925533894599),
 (4163, 0.10540925533894599),
 (4331, 0.10540925533894599),
 (4566, 0.10540925533894599),
 (4623, 0.10540925533894599),
 (41, 0.10476454436543672),
 (103, 0.10476454436543672),
 (170, 0.10476454436543672),
 (371, 0.10476454436543672),
 (782, 0.10476454436543672),
 (129, 0.10350983390135313),
 (475, 0.10350983390135313),
 (543, 0.10350983390135313),
 (595, 0.10350983390135313),
 (4121, 0.10350983390135313),
 (88, 0.1025978352085154),
 (144, 0.1025978352085154),
 (165, 0.1025978352085154),
 (259, 0.1025978352085154),
 (276, 0.1025978352085154),
 (336, 0.1025978352085154),
 (498, 0.1025978352085154),
 (626, 0.1025978352085154),
 (1682, 0.1025978352085154),
 (2087, 0.1025978352085154),
 (2350, 0.1025978352085154),
 (2758, 0.1025978352085154),
 (3626, 0.1025978352085154),
 (4271, 0.1025978352085154),
 (4316, 0.1025978352085154),
 (4357, 0.1025978352085154),
 (1414, 0.10229915092057101),
 (2646, 0.10229915092057101),
 (2001, 0.10112997936948631),
 (2709, 0.10112997936948631),
 (4179, 0.10112997936948631),
 (152, 0.09999999999999999),
 (196, 0.09999999999999999),
 (245, 0.09999999999999999),
 (266, 0.09999999999999999),
 (309, 0.09999999999999999),
 (319, 0.09999999999999999),
 (476, 0.09999999999999999),
 (604, 0.09999999999999999),
 (672, 0.09999999999999999),
 (773, 0.09999999999999999),
 (951, 0.09999999999999999),
 (1078, 0.09999999999999999),
 (1135, 0.09999999999999999),
 (1345, 0.09999999999999999),
 (1699, 0.09999999999999999),
 (1709, 0.09999999999999999),
 (1766, 0.09999999999999999),
 (2171, 0.09999999999999999),
 (2391, 0.09999999999999999),
 (2575, 0.09999999999999999),
 (2676, 0.09999999999999999),
 (2737, 0.09999999999999999),
 (3131, 0.09999999999999999),
 (836, 0.09890707100936805),
 (1320, 0.09890707100936805),
 (29, 0.09784921095801634),
 (143, 0.09784921095801634),
 (768, 0.09784921095801634),
 (1493, 0.09784921095801634),
 (1920, 0.09784921095801634),
 (2998, 0.09784921095801634),
 (104, 0.09759000729485331),
 (237, 0.09759000729485331),
 (358, 0.09759000729485331),
 (617, 0.09759000729485331),
 (660, 0.09759000729485331),
 (668, 0.09759000729485331),
 (1257, 0.09759000729485331),
 (1260, 0.09759000729485331),
 (1325, 0.09759000729485331),
 (1360, 0.09759000729485331),
 (1715, 0.09759000729485331),
 (1856, 0.09759000729485331),
 (2086, 0.09759000729485331),
 (2144, 0.09759000729485331),
 (2517, 0.09759000729485331),
 (3659, 0.09759000729485331),
 (3952, 0.09759000729485331),
 (4194, 0.09759000729485331),
 (4201, 0.09759000729485331),
 (183, 0.09682458365518543),
 (277, 0.09682458365518543),
 (777, 0.09682458365518543),
 (2131, 0.09682458365518543),
 (2435, 0.09682458365518543),
 (1688, 0.09583148474999098),
 (82, 0.09534625892455922),
 (90, 0.09534625892455922),
 (95, 0.09534625892455922),
 (227, 0.09534625892455922),
 (236, 0.09534625892455922),
 (290, 0.09534625892455922),
 (356, 0.09534625892455922),
 (368, 0.09534625892455922),
 (449, 0.09534625892455922),
 (1083, 0.09534625892455922),
 (1239, 0.09534625892455922),
 (1287, 0.09534625892455922),
 (1467, 0.09534625892455922),
 (1509, 0.09534625892455922),
 (1627, 0.09534625892455922),
 (1880, 0.09534625892455922),
 (2585, 0.09534625892455922),
 (3345, 0.09534625892455922),
 (3837, 0.09534625892455922),
 (4290, 0.09534625892455922),
 (4355, 0.09534625892455922),
 (4468, 0.09534625892455922),
 (1367, 0.09486832980505137),
 (1874, 0.09486832980505137),
 (2252, 0.0939336436627724),
 (2494, 0.0939336436627724),
 (2966, 0.0939336436627724),
 (307, 0.09376144618769908),
 (78, 0.09325048082403138),
 (142, 0.09325048082403138),
 (711, 0.09325048082403138),
 (840, 0.09325048082403138),
 (1430, 0.09325048082403138),
 (1684, 0.09325048082403138),
 (1786, 0.09325048082403138),
 (1989, 0.09325048082403138),
 (2049, 0.09325048082403138),
 (2116, 0.09325048082403138),
 (2239, 0.09325048082403138),
 (2558, 0.09325048082403138),
 (3150, 0.09325048082403138),
 (3164, 0.09325048082403138),
 (4254, 0.09325048082403138),
 (4270, 0.09325048082403138),
 (572, 0.09302605094190634),
 (661, 0.09302605094190634),
 (755, 0.09302605094190634),
 (1674, 0.09302605094190634),
 (2545, 0.09302605094190634),
 (75, 0.09128709291752769),
 (198, 0.09128709291752769),
 (219, 0.09128709291752769),
 (325, 0.09128709291752769),
 (339, 0.09128709291752769),
 (341, 0.09128709291752769),
 (362, 0.09128709291752769),
 (370, 0.09128709291752769),
 (389, 0.09128709291752769),
 (544, 0.09128709291752769),
 (597, 0.09128709291752769),
 (778, 0.09128709291752769),
 (1007, 0.09128709291752769),
 (1025, 0.09128709291752769),
 (1030, 0.09128709291752769),
 (1077, 0.09128709291752769),
 (1132, 0.09128709291752769),
 (1194, 0.09128709291752769),
 (1465, 0.09128709291752769),
 (1792, 0.09128709291752769),
 (2618, 0.09128709291752769),
 (2820, 0.09128709291752769),
 (2861, 0.09128709291752769),
 (3374, 0.09128709291752769),
 (3609, 0.09128709291752769),
 (4490, 0.09128709291752769),
 (4519, 0.09128709291752769),
 (153, 0.09128709291752768),
 (301, 0.09128709291752768),
 (607, 0.09128709291752768),
 (1570, 0.09128709291752768),
 (51, 0.09045340337332908),
 (222, 0.09045340337332908),
 (2594, 0.09045340337332908),
 (2756, 0.09045340337332908),
 (1824, 0.08964214570007953),
 (8, 0.08944271909999159),
 (112, 0.08944271909999159),
 (167, 0.08944271909999159),
 (195, 0.08944271909999159),
 (220, 0.08944271909999159),
 (644, 0.08944271909999159),
 (937, 0.08944271909999159),
 (1588, 0.08944271909999159),
 (1645, 0.08944271909999159),
 (2018, 0.08944271909999159),
 (2264, 0.08944271909999159),
 (3536, 0.08944271909999159),
 (3633, 0.08944271909999159),
 (3803, 0.08944271909999159),
 (3888, 0.08944271909999159),
 (3366, 0.08899883189799696),
 (193, 0.08808303292720551),
 (37, 0.08770580193070293),
 (235, 0.08770580193070293),
 (282, 0.08770580193070293),
 (306, 0.08770580193070293),
 (510, 0.08770580193070293),
 (754, 0.08770580193070293),
 (805, 0.08770580193070293),
 (956, 0.08770580193070293),
 (1029, 0.08770580193070293),
 (1544, 0.08770580193070293),
 (1806, 0.08770580193070293),
 (2231, 0.08770580193070293),
 (2552, 0.08770580193070293),
 (3091, 0.08770580193070293),
 (3107, 0.08770580193070293),
 (3253, 0.08770580193070293),
 (3450, 0.08770580193070293),
 (4602, 0.08770580193070293),
 (4799, 0.08770580193070293),
 (55, 0.08660254037844385),
 (2, 0.08606629658238704),
 (24, 0.08606629658238704),
 (115, 0.08606629658238704),
 (240, 0.08606629658238704),
 (257, 0.08606629658238704),
 (335, 0.08606629658238704),
 (664, 0.08606629658238704),
 (745, 0.08606629658238704),
 (1086, 0.08606629658238704),
 (1139, 0.08606629658238704),
 (1742, 0.08606629658238704),
 (1755, 0.08606629658238704),
 (2296, 0.08606629658238704),
 (2648, 0.08606629658238704),
 (3037, 0.08606629658238704),
 (3299, 0.08606629658238704),
 (3355, 0.08606629658238704),
 (3990, 0.08606629658238704),
 (4146, 0.08606629658238704),
 (4320, 0.08606629658238704),
 (38, 0.08588975014708022),
 (4305, 0.08588975014708022),
 (160, 0.08519427513705971),
 (3860, 0.08519427513705971),
 (21, 0.08451542547285165),
 (40, 0.08451542547285165),
 (185, 0.08451542547285165),
 (291, 0.08451542547285165),
 (302, 0.08451542547285165),
 (485, 0.08451542547285165),
 (503, 0.08451542547285165),
 (1291, 0.08451542547285165),
 (1436, 0.08451542547285165),
 (1526, 0.08451542547285165),
 (1697, 0.08451542547285165),
 (1743, 0.08451542547285165),
 (1828, 0.08451542547285165),
 (2163, 0.08451542547285165),
 (2220, 0.08451542547285165),
 (2249, 0.08451542547285165),
 (3632, 0.08451542547285165),
 (3924, 0.08451542547285165),
 (3933, 0.08451542547285165),
 (59, 0.08451542547285164),
 (426, 0.08451542547285164),
 (3615, 0.08385254915624211),
 (116, 0.08304547985373996),
 (254, 0.08304547985373996),
 (294, 0.08304547985373996),
 (365, 0.08304547985373996),
 (454, 0.08304547985373996),
 (645, 0.08304547985373996),
 (687, 0.08304547985373996),
 (741, 0.08304547985373996),
 (834, 0.08304547985373996),
 (901, 0.08304547985373996),
 (932, 0.08304547985373996),
 (1009, 0.08304547985373996),

In [64]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(151, 0.26967994498529685),
 (4405, 0.25819888974716115),
 (942, 0.24913643956121986),
 (1440, 0.2480694691784169),
 (1192, 0.2439750182371333)]

In [65]:
similarity[0].shape

(4806,)

# Main Function

In [66]:
def recommend(movie):       # main fn : takes a movie as an argument and find its index and would see similarity[i] and return top 5 movies on basis of top 5 similarities
    movie_index = new_df[new_df['title']==movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
            print(new_df.iloc[i[0]].title)

In [67]:
new_df.iloc[2999].title

'The Boy'

In [68]:
recommend('Avatar')

Beowulf
The Helix... Loaded
The Book of Life
Krull
Small Soldiers

In [ ]:
import pickle
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [71]:
import pickle
import numpy as np

similarity = pickle.load(open('similarity.pkl', 'rb'))
similarity = similarity.astype(np.float32)

# Save with highest compression
import gzip
with gzip.open('similarity.pkl', 'wb', compresslevel=9) as f:
    pickle.dump(similarity, f)

import os
size = os.path.getsize('similarity.pkl') / (1024*1024)
print(f"New size: {size:.1f} MB")

New size: 29.3 MB

In [73]:
import gzip
import streamlit as st

@st.cache_data
def load_data():
    movies_dict = pickle.load(open('movie_dict.pkl', 'rb'))
    movies = pd.DataFrame(movies_dict)
    with gzip.open('similarity.pkl', 'rb') as f:
        similarity = pickle.load(f)
    return movies, similarity

2026-05-05 16:30:19.869 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

# Deployment